name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch name
  pull_request:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner tag here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t pclass-shaheryar .

  deploy:
    runs-on: self-hosted  # Use your self-hosted runner tag here
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Docker container
        run: |
          echo "Deploying Docker container..."
          docker stop pclass-shaheryar || true
          docker rm pclass-shaheryar || true
          docker run -d --name pclass-shaheryar -p 81:80 pclass-shaheryar

  test:
    runs-on: self-hosted  # Use your self-hosted runner tag here
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test server
        run: |
          echo "Testing if the server is up..."
          sleep 10
          if [[ $(curl -s -o /dev/null -w "%{http_code}" http://103.172.26.36:81) != "200" ]]; then
            exit 1
          fi
